BOT_TOKEN = "5308312465:AAFOSMsTJc2bKNLSv1kzBkN1t1aTiGNBjXs"
WEBHOOK_HOST = "your_domain.com"
WEBHOOK_PATH = "/web_app_example"
WEBHOOK_URL = f"{WEBHOOK_HOST}{WEBHOOK_PATH}"
WEBAPP_HOST = "0.0.0.0"
WEBAPP_PORT = 8000
